version: '2'
services:
  db:
    image: mariadb:latest
    ports: 
      - "3306:3306"
#    volumes:
#      - '/srv/sailpoint-docker/db:/var/lib/mysql'
    environment:
      - MYSQL_USER=identityiq
      - MYSQL_PASSWORD=identityiq
      - MYSQL_DATABASE=identityiq
      - MYSQL_ROOT_PASSWORD=password
  iiq:
    build: ./iiq-build
    image: sailpoint-iiq
    ports:
      - "8888:8080"
      - "9009:8009"
    environment:
      - MYSQL_USER=identityiq
      - MYSQL_PASSWORD=identityiq
      - MYSQL_DATABASE=identityiq
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db
#    volumes:
#    - "/srv/sailpoint-docker/webapps/:/opt/tomcat/webapps/"
